[paths]

db_path = 'output/multiframe/multiframe.db'
schema_path = 'doc/db_schema.sql'
output_path = 'output/multiframe/'
fasta_path = 'libraries/multiframe/reporters.fa'

[constants]
adaptor_5p = 'GAATACAAGCCCTACACGACGCTCTTCCGATCT'
adaptor_3p = 'CGAGGAGCTCGACTACAAAGACGACGACGACAAACTATCCTTACGACGTCCCAGACTACGCACGAACAAAAACTTATATCGGAGGAAGACCTCAGATTACAAGGACGACGACGACAAGATATCCCTACGACGTTCCGGACTACGCCAGAGCAAAAACTCATTTCAGAAGAGGATTTGGGATTACAAAGACGACGACGACAAAGTATCCTTACGACGTACCGGATTACGCAGGAGCAGAAACTTATATCGGAAGAAGACTTGGGAATTATTTACTGGTGTGGTACCCATATTGGTGGAATTGGACGGGGACGTCAACGGGCACAAATTTTCTGTCTCTGGAGAGGGAGAGGGAGACGCCACATACGGGAAACTCACTCTCAAGTTTATCTGTACCACCGGGAAATTACCTGTACCGTGGCCTACGCTGGTTACTACTCTTACATACGGGGTACAGTGCTTTTCTCGATATCCGGACCATATGTCTCAGCACGACTTCTTCAAAAGCGCGATGCCAGAAGGATACGTACAGGAAAGGACCATATTCTTCAAGGACGACGGGAATTACAAGACAAGAGCAGAAGTCAAATTCGAAGGGGATACGCTGGTCAACAGGATCGAACTCAAGGGGATCGATTTCAAGGAAGACGGGAACATACTTGGTCACAAATTGGAATACAACTACAATTCGCACAACGTATACATTATGGCGGACAAGCAGAAGAACGGGATCAAAGTCAATTTCAAGATACGTCACAATATCGAGGACGGATCTGTACAATTGGCAGACCATTACCAACAGAACACACCGATTGGGGACGGTCCGGTATTATTACCAGACAATCACTATCTATCTACCCAATCTGCGCTATCCAAGGATCCGAACGAGAAAAGAGATCATATGGTATTACTGGAATTTGTTACGGCTGCTGGGATCACGCTGGGGATGGACGAGCTATACAAGAAATTGGGAGGTGGATCTGGTGGTGGAAGTGTATTCACGTTGGAAGATTTCGTTGGGGATTGGCGTCAGACTGCTGGATACAATCTGGATCAGGTGTTGGAGCAAGGTGGTGTATCCAGCTTATTCCAGAATCTTGGAGTATCGGTTACTCCCATACAGAGGATCGTGTTATCTGGAGAGAACGGGCTCAAGATCGATATACACGTCATTATACCGTACGAAGGGCTATCTGGAGATCAAATGGGGCAGATCGAGAAGATATTCAAAGTGGTATATCCTGTGGACGACCATCATTTCAAAGTCATACTACACTACGGTACGTTGGTCATCGACGGTGTCACTCCGAACATGCTCGATTACTTTGGTCGACCGTACGAGGGGATTGCGGTATTCGACGGGAAGAAGATTACGGTTACTGGGACTCTTTGGAACGGGAACAAGATCATCGACGAAAGGCTCATCAATCCGGACGGATCGCTGCTATTCCGTGTTACGATCAACGGTGTCACTGGCTGGCGGCTTTGCGAACGGATACTGGCCACCGTGGATATCAAGCTGCCGTGGCTGCAGTCGTCGCTGGGACGCTGCAGACGTACTACGATCAAGGATTTGGGACGGATCGTCCTCCTGCTGCTTACGTTTTTGCTCAGATCAAAGATAATGATAGACCGTGGATCTCGAGTTGTCGGGGCTGCTCCCGCCGTTGGGACGCCGCGGACGTGTTGCGCTCAAGAATTTGGGACGGCTCATCGTCGTGCTGCCTCAGATTTTGCAAGGACCAGCGATAATGATAGACCGTGGATCTCAAGTTGCCGGGGGTGTTCACGAAGGTGGGACGCAGCCGACGTCCTGCGATCCCGCATCTGGGACGGCTCGAGCAGCTGTTGTCTTCGCTTCTGTACGGATCAGAGGTAATGATAGctcgagcctctagaactatagtgagtcgtattacgtagatccagacatgataaga'
main_orf_start = -14
kozak_score_path = 'doc/kozak.json'

[features]
orf_finder = [{start_codons = ['ATG']}]

[data.functions]
calculate_delta = [{samples = ['mf_fish_test'], num_run_type = 'flag_pulldown', denom_run_type = 'input', data_type = 'FLAG-translation'},{samples = ['mf_fish_test'], num_run_type = 'ha_pulldown', denom_run_type = 'input', data_type = 'HA-translation'},{samples = ['mf_fish_test'], num_run_type = 'myc_pulldown', denom_run_type = 'input', data_type = 'MYC-translation'}]

[data.count_paths]
ntrap_multiframe_pilot = 'data/multiframe/ntrap_multiframe_counts.json'

[data.samples.mf_fish_test]
experiment_name = 'ntrap_multiframe_pilot'
collection_time = 6
library = '60A'
organism = 'Danio rerio'

[data.samples.mf_fish_test.runs]
AGR004938 = {replicate_name = 'B1', run_type = 'input'}
AGR004939 = {replicate_name = 'B2', run_type = 'input'}
AGR004932 = {replicate_name = 'B1', run_type = 'flag_pulldown'}
AGR004933 = {replicate_name = 'B2', run_type = 'flag_pulldown'}
AGR004934 = {replicate_name = 'B1', run_type = 'ha_pulldown'}
AGR004935 = {replicate_name = 'B2', run_type = 'ha_pulldown'}
AGR004936 = {replicate_name = 'B1', run_type = 'myc_pulldown'}
AGR004937 = {replicate_name = 'B2', run_type = 'myc_pulldown'}








