[paths]

db_path = 'output/kozak/kozak.db'
schema_path = 'doc/db_schema.sql'
output_path = 'output/kozak/'
fasta_path = 'libraries/kozak/reporters.fa'


[constants]

adaptor_5p = 'GAATACAAGCCCTACACGACGCTCTTCCGATCTATACAAGCTACTTGTTCTTTTTGCAGGAGCC'
adaptor_3p = 'TGAGCAAGGGCGAGGACTACAAAGACCATGACGGTGATTATAAAGATCATGACATCGATTACAAGGATGACGATGACAAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAACAGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGTGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGACGAGCTGTACAAGAAGCTTAGCCATGGCTTCCCGCCGGCGGTGGCGGCGCAGGATGATGGCACGCTGCCCATGTCTTGTGCCCAGGAGAGCGGGATGGACCGTCACCCTGCAGCCTGTGCTTCTGCTAGGATCAATGTGTGACTCGAGCCTCTAGAACTATAGTGAGTCGTATTACGTAGATCCAGACATGATAAGA'
main_orf_start = -4
kozak_score_path = 'doc/kozak.json'


[features]
kmer_counter = [{kmax = 3}]
hot_encoded = [{kmax = 3, pos_to_exclude = [6,7,8], pos_0 = false }]
orf_finder = [{start_codons = ['ATG']}]


[data]
ignore_not_found = true

[data.count_paths]
ntrap_fish_kozak = 'data/kozak/ntrap_kozak_counts.json'

[data.functions]
calculate_delta = [{samples = ['kozak_6h'], num_run_type = 'flag_pulldown', denom_run_type = 'input', data_type = 'translation'}]

[data.samples.kozak_6h]
experiment_name = 'ntrap_fish_kozak'
collection_time = 6
library = '60A'
organism = 'Danio rerio'

[data.samples.kozak_6h.runs]
ESF2-ACTTGA = {replicate_name = 'B1', run_type = 'flag_pulldown'}
ESF2-CTAGCT = {replicate_name = 'B2', run_type = 'flag_pulldown'}
ESF4-ACTTGA = {replicate_name = 'B1', run_type = 'input'}
ESF4-CTAGCT = {replicate_name = 'B2', run_type = 'input'}