[selectors]

[selectors.polyA_fish]
sample_names = ['pa_2hpf', 'pa_6hpf']
data_types = ['mean_translation']
read_filters = [['input','raw_count', '100']]
features_to_include = []
features_to_exclude = []
filter_features = []

[selectors.sv40_fish]
sample_names = ['sv40_2hpf', 'sv40_6hpf']
data_types = ['mean_translation']
read_filters = [['input','raw_count', '100']]
features_to_include = []
features_to_exclude = []
filter_features = []

[selectors.polyA_fish_hek293t]
sample_names = ['pa_2hpf', 'pa_6hpf', 'hek293t_12h']
data_types = ['mean_translation']
read_filters = [['input','raw_count', '100']]
features_to_include = []
features_to_exclude = []
filter_features = []

[selectors.polyA_hek293t]
sample_names = ['hek293t_12h']
data_types = ['mean_translation']
read_filters = [['input','raw_count', '100']]
features_to_include = []
features_to_exclude = []
filter_features = []
